# -*- coding: utf-8 -*-
"""
Created on Fri Nov 19 09:40:41 2021

@author: erkol
"""
seq="ATCTCCACGCTTTTATCATAAAATCCACCAGGCCAGGTGTGGACAATGGTGGACCTCGGTGGCTGAACTATGCAGTGCACGCTGACAGCACACGCATTCCTCATGCTTATTTCTATGGTTAAACGGGTGTATCACCCGCAAGCGAGAAGACTGTTTGGGCAGGTGCATGACTTAGCCAGTATCTCCTCCTCGTCAAAGAGGGGTTGATGTACAAGGTCAGAACGGCGGTAATCACATACAAATTCACGGAATAAGCTATGGAATGAGGCCAACCGTCTCCGATTATGCCCATCGAAATATTGAGAATAAGCGGACTCCGATCAGCGCGAAGAAACGGCCTGGTAACTTGACGTGTACCCTATTCAAACATCAGGCCCGTCGGATTAGTCGGGTGGGTCCGCATGAGAACAAGCCGGCTACCGTAATGCCAAGGCCAACGTGTGAAAGATTGATCGTGCAGCTCGCATAGGTGCCAATACTGCTAATTATGGTTGGCTACCAATTCAGTTTACTACCGCTCTGACCAAACCAATTAAAACTTTAAGGTAATCGATATGCTCAACCCTCAGATCTACAGGATGATGGGATATTGAACCTAATTACGGCGCGGGCCTGGCCGCGATTGCTGCAGGGTGAAATATATAAACGCGGCCCCACCGTGGACGGTAAAGCATCGGTCAGGCCACCGAGAGCCTTTCCAGCCCTGGTTGTTACGACTGGCAATCTCCAAGGTCGACACCCACTTTTGAAAAGCTGGTTCGACAGAAAAGCGACCCATTCCACTCGCGTGATCCCGGAGGCGCCATTTTCCCTCGCTGGAGGCCGCTACTGACGAGCTGCTCTGAATATAGACCCCCCTCACGCCGTCGCTGACCACGCTGACGCACAGGCAATAGGATTGATTCTCCCTAGATACGCACAGGAGGCATCTTGGCC"

rseq=seq[::-1]
t=list(rseq)
if len(rseq) <= 1000:
    for i in range(len(rseq)):
        if t[i]=='T':
            t[i]='A'  
        elif t[i]=='A':
            t[i]='T'  
        elif t[i]=='C':
            t[i]='G'
        elif t[i]=='G':
            t[i]='C'
    
    
delimiter=''
u=delimiter.join(t)
print(u)