# -*- coding: utf-8 -*-
"""
Created on Thu Oct 14 18:36:13 2021

@author: erkol
"""
s='GCCCAGACAGCTGCGACATAGGGGGCTGTCTCTATAGCCCCGTGCGACCGGAGCCAATATTGCAGGTCCAAACTGGAAAACCACCGGACCCCTACTCCTGTGTGGCGCATGTGCGGCAAGTCTACCACCATGCTGGGTCGGGCCGCAAGTAGGTCTACCAAATCGAGAAAAGGGCGTACAGAGACAAGGTAGCTTTGGCTATTAGTACGGAGACCCGGTCTGTGATGACGGCATAAAGCTTTCGACGACTGGCGTCTACGGATGACAGACTTGGCGACGCTAAGTCTAGAGAGATAGTTTATGACCCGCTGGACCCTACGTTGAAAGCCAAGCGCAATTGTTGGCTTAAGCAACTTTCGGACAAGATTGGTATGTCACAAGGGGAGGGTCAATTCAGGCAGCCTCATTATAGGTGTACTTTTCGAGGATAAAGCGGTGATAGCTGTAAGTCGTGGTGTCGACCCCCCGATGCTATGTCTTCAGGACACGTGTCGAGCGACCTGTAGTGTTGTTGTGTACTATAGAACTTTGAGCTCCACTCGTATCCCAATATCTCGACCGCGGGGTGCGCTTGCCAGAATCAATAAGACAAGTCAGACCTGCCTGTGTCCAGTGGTCCCGGTTAGGCCGAGCTGATTCGAGAGGTCTAGTTCCCGCTCATACGAGCACCCCTTTACCGCGGAGAGGGGGGGACGTGTCCTGCTATATCATTCGGACTTAGGTACGAGAAGAACTGAGGGAAAACAATGTAACAGAAGAGACTGTCTCTTTTGTCTATCATCGATGCAACGATAGTGTTAAACGGGTGCTAGACGGCTCACGGTTTAACACTGCTCATTCCCTTTCCACGTTGCAGGTAAGACACCTCTTTAAATTATACTCACACAAGCAATCGCGCGGTAGGGTTTCTTAACTCTATGATCTCCCATGGGTATCGGAACATCGCACTGAATCTACCAAGTCGCCC'

t=list(s)
if len(s) <= 1000:
    for i in range(len(s)):
        if t[i]=='T':
            t[i]='U'  

delimiter=''
u=delimiter.join(t)
print(u)
        

